```{r}
source('discretize.R')
library(dplyr)
raw_data <- read.csv('data/Peru_TB_data.csv')

floor_median <- function(x) {
  return(floor(median(x, na.rm=TRUE)))
}

preprocess <- function(data) {
  # define binary outcome (y)
  data$adherence_outcome <- ifelse(data$PCTadherence_sensi < 95, 1, 0)
  
  # drop subsequent regimens
  data <- data %>%
    filter(regimen == "first") %>%
    select(-regimen)
  
  # drop X, patient id, and other variables we don't want to include in our model
  data <- data %>% select(-c(X, # index
                             prop_misseddoses_int, # not in dictionary
                             PCTadherence,
                             PCTadherence_sensi,
                             PTID2, # study ID
                             hunger_freq, # "not including in the model"
                             health_ctr, # 71 health centers ,
                             daily_cont, # not in dictionary
                             post_tb_pt_work)) #  not in dictionary
  
  # family support - simplify by taking median response to get almost integer value
  fam_vars <- c("fam_affection", "fam_parent_getalong", "fam_others_getalong",
                "fam_confide", "fam_parent_emosupport", "fam_others_emosupport",
                "fam_support_others", "fam_satisfied")
  data$family_median <- apply(data[, fam_vars], 1, floor_median)
  data <- data %>% select(-all_of(c(fam_vars, "fam_support")))
  
  # evaluation of health services
  health_serv_vars <- c("aten_wait", "aten_respect", "aten_explain", "aten_space",
                        "aten_concern","aten_satis_hours")
  data$health_svc_median <- apply(data[, health_serv_vars],
                                   1, floor_median)
  data <- data %>% select(-all_of(c(health_serv_vars, "healthsvc_satis")))
  
  # motivation
  motivation_vars <- c("motiv_no_transmit", "motiv_fam_worry", "motiv_study_work",
                       "motiv_activities")
  data$motiv_median <- apply(data[, motivation_vars], 1, floor_median)
  data <- data %>% select(-all_of(c(motivation_vars,  "motiv_summary")))
  
  # tb disinformation
  knowledge_vars <- c("conoc_cure", "conoc_missed_doses", "conoc_default")
  data$knowledge_median <- apply(data[, knowledge_vars], 1, floor_median)
  data <- data %>% select(-all_of(c(knowledge_vars,  "tb_knowledge")))
  
  # pills and adr_freq need to multiplied by 4 - does not match data dictionary
  data$pills <- 4*data$pills
  data$adr_freq <- 4*data$adr_freq
  
  # change to categorical
  data$current_sx_none <- as.factor(data$current_sx_none)
  data$tto_anterior_tb <- as.factor(data$tto_anterior_tb)
  data$monitor1 <- as.factor(data$monitor1)
  
  data <- na.omit(data)
  
  # some categorical variable have levels with few observations
  # drop ram and regular_drug since only 5 observations in class 1
  data <- data %>% select(-c(ram, regular_drug))

  # education levels could be combined but we drop since not
  # included in data documentation and unclear best way to relevel
  data <- data %>% select(-c(edu_level_mom, edu_level_dad))
  
  non_numeric_columns <- names(data)[!sapply(data, is.numeric)]
  data[non_numeric_columns] <- lapply(data[non_numeric_columns], as.factor)
  
  return(data)
}

df <- preprocess(raw_data)
X <- df %>% select(-adherence_outcome, -audit_tot) 
y <- df %>% pull(adherence_outcome) # get target column as vector

cont_cols <- c("self_eff", "tx_mos", "stig_tot",
              "phq9_tot", "age_BLchart", "ace_score")
```


```{r, warning=FALSE}
disc_X_10 <- discretize(X, y, continuous_cols = cont_cols)
disc_X_5 <- discretize(X, y, continuous_cols = cont_cols, n_quantiles = rep(5, length(cont_cols)))
disc_X_3 <- discretize(X, y, continuous_cols = cont_cols, n_quantiles = rep(3, length(cont_cols)))
```

```{r, warning=FALSE}
get_results <- function(disc_X) {
  disc_df = disc_X
  disc_df$y = y
  
  # model matrix and save
  mat <- model.matrix(y ~ ., data=disc_df)
  mat <- cbind(mat, y = disc_df$y)
  X_rm = as.matrix(mat[,-ncol(mat)])
  y_rm = as.matrix(mat[,ncol(mat)])
    
  mod <- risk_mod(X = X_rm, y = y_rm)
  obj <- obj_fcn(mod$X, mod$y, mod$gamma, mod$beta, mod$weights, mod$lambda0)
  card <- mod$model_card
  return(list(mod, obj, card))
}
```

```{r, warning=FALSE}
res10 <- get_results(disc_X_10)
res5 <- get_results(disc_X_5)
res3 <- get_results(disc_X_3)
```

```{r, warning=FALSE}
t01q10 <- get_results(discretize(X, y, continuous_cols = cont_cols))
t05q10 <- get_results(discretize(X, y, continuous_cols = cont_cols,  
                                 threshold = 0.05))
t001q10 <- get_results(discretize(X, y, continuous_cols = cont_cols,
                                  threshold = 0.001))
t005q10 <- get_results(discretize(X, y, continuous_cols = cont_cols,  
                                 threshold = 0.005))
```

```{r, warning=FALSE}
disc_X_345533 <- discretize(X, y, continuous_cols = cont_cols, n_quantiles=c(3,4,5,5,3,3))
res_345533 <- get_results(disc_X_345533)

disc_X_234422 <- discretize(X, y, continuous_cols = cont_cols, n_quantiles=c(2,3,4,4,2,2))
res_234422 <- get_results(disc_X_234422)

disc_X_456644 <- discretize(X, y, continuous_cols = cont_cols, n_quantiles=c(4,5,6,6,4,4))
res_456644 <- get_results(disc_X_456644)

disc_X_446644 <- discretize(X, y, continuous_cols = cont_cols, n_quantiles=c(4,4,6,6,4,4))
res_446644 <- get_results(disc_X_446644)
```

```{r, warning=FALSE}
compare_df <- data.frame(X$age_BLchart, tb_df$age_cat, disc_X_10$age_BLchart,
                         disc_X_5$age_BLchart, disc_X_3$age_BLchart)
```